# Generated by Django 2.2.4 on 2019-08-17 21:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20190817_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bien',
            name='area',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Area'),
        ),
        migrations.AlterField(
            model_name='bien',
            name='estado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Estado'),
        ),
        migrations.AlterField(
            model_name='bien',
            name='persona',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Persona'),
        ),
        migrations.AlterField(
            model_name='bien',
            name='tipo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Tipo'),
        ),
    ]
