# Generated by Django 2.2.4 on 2019-08-18 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20190817_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='bien',
            name='fecha',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='bien',
            name='serial',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='bien',
            name='valor',
            field=models.IntegerField(null=True),
        ),
    ]
